In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib as mpl
import random
import pipe

Let's test out all the fun examples in the Boston.gov Data API

In [1]:
import json
import urllib.request
url = 'https://data.boston.gov/api/3/action/datastore_search?resource_id=dc615ff7-2ff3-416a-922b-f0f334f085d0&limit=5&q=title:jones'  
fileobj = urllib.request.urlopen(url)
response_dict = json.loads(fileobj.read())
print(response_dict)

KeyboardInterrupt:

In [15]:
"1850-to-1899.csv'
'1900-to-1919.csv'
'1920-to-1929.csv'
'1930-to-1939.csv'
'1940-to-1949.csv'
'1950-to-1959.csv'
'1960-to-1969.csv'
'1970-to-1979.csv'
'1980-to-1999.csv'
'2016-to-2022.csv'


sample_1800 = pd.read_csv(
    '1800-to-1849.csv',
    header=0, 
    skiprows=lambda i: i>0 and random.random() > .01
    )

sample_1800.head()

,rs_prop_sam_id,rs_prop_prim_sam_id,rs_prop_full_address,rs_prop_street_number,rs_prop_full_street_name,rs_prop_unit_number,rs_prop_zip_code,rs_prop_mailing_neighborhood,rs_prop_long,rs_prop_lat,...,json_bldg_mhl_housing_3year,json_mhl_housing_5year,json_bldg_mhl_housing_5year,json_mhl_sanitation_1year,json_bldg_mhl_sanitation_1year,json_mhl_sanitation_3year,json_bldg_mhl_sanitation_3year,json_mhl_sanitation_5year,json_bldg_mhl_sanitation_5year,json_all_owner_props
0,227292,50325,13 Dwight St #2,13,Dwight St,2.0,2118,Roxbury,-71.06813,42.34420,...,NaN,NaN,NaN,"[{""date"":""2021-06-01T10:04:00"",""description"":""...","[{""date"":""2020-09-08T14:40:16.643"",""descriptio...","[{""date"":""2021-06-01T10:04:00"",""description"":""...","[{""date"":""2020-09-08T14:40:16.643"",""descriptio...","[{""date"":""2021-06-01T10:04:00"",""description"":""...","[{""date"":""2020-09-08T14:40:16.643"",""descriptio...","[{""rs_prop_owner"":""CURTIS PAUL A TS"",""rs_prop_..."
1,98882,167936,8 Mount Vernon St,8,Mount Vernon St,NaN,2129,Charlestown,-71.05883,42.37583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""rs_prop_owner"":""GILDEA ANN"",""rs_prop_full_a..."
2,281,281,7 Acorn St,7,Acorn St,NaN,2108,Boston,-71.06905,42.35750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""rs_prop_owner"":""GOFF EDWARD F III"",""rs_prop..."
3,93998,93998,6 Melrose St,6,Melrose St,NaN,2116,Boston,-71.06741,42.34952,...,NaN,NaN,NaN,"[{""date"":""2020-12-08T20:31:51.563"",""descriptio...",NaN,"[{""date"":""2020-12-08T20:31:51.563"",""descriptio...",NaN,"[{""date"":""2020-12-08T20:31:51.563"",""descriptio...",NaN,"[{""rs_prop_owner"":""HARCUS PORTIA G"",""rs_prop_f..."
4,36093,36093,9 Columbus Sq,9,Columbus Sq,NaN,2118,Roxbury,-71.07798,42.34316,...,NaN,NaN,NaN,"[{""date"":""2021-04-06T10:39:57.847"",""descriptio...",NaN,"[{""date"":""2021-04-06T10:39:57.847"",""descriptio...",NaN,"[{""date"":""2021-04-06T10:39:57.847"",""descriptio...",NaN,"[{""rs_prop_owner"":""NINE COLUMBUS SQ CONDO TR"",..."

In [ ]:
'1900-to-1919.csv'
'1920-to-1929.csv'
'1930-to-1939.csv'
'1940-to-1949.csv'
'1950-to-1959.csv'
'1960-to-1969.csv'
'1970-to-1979.csv'
'1980-to-1999.csv'
'2016-to-2022.csv'
ct = 0
with open('1850-to-1899.csv') as f:
    len(count.fields(f))

# sample_1850 = pd.read_csv(
#     '1850-to-1899.csv'
#     , header = 0
#     , nrows = 10
#     )

# sample_1850.head()

In [22]:
'1920-to-1929.csv'
'1930-to-1939.csv'
'1940-to-1949.csv'
'1950-to-1959.csv'
'1960-to-1969.csv'
'1970-to-1979.csv'
'1980-to-1999.csv'
'2016-to-2022.csv'


sample_1900 = pd.read_csv(
    '1900-to-1919.csv'
    , header = 0
    , nrows = 10
    )

sample_1900.head()

,rs_prop_sam_id,rs_prop_prim_sam_id,rs_prop_full_address,rs_prop_street_number,rs_prop_full_street_name,rs_prop_unit_number,rs_prop_zip_code,rs_prop_mailing_neighborhood,rs_prop_long,rs_prop_lat,...,json_bldg_mhl_housing_3year,json_mhl_housing_5year,json_bldg_mhl_housing_5year,json_mhl_sanitation_1year,json_bldg_mhl_sanitation_1year,json_mhl_sanitation_3year,json_bldg_mhl_sanitation_3year,json_mhl_sanitation_5year,json_bldg_mhl_sanitation_5year,json_all_owner_props
0,42986,42986,243 Cornell St,243,Cornell St,NaN,2131,Roslindale,-71.136400,42.28031,...,NaN,"[{""date"":""2016-07-25T11:01:00"",""description"":""...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""rs_prop_owner"":""DALY MAUREEN C"",""rs_prop_fu..."
1,97889,97889,27 Moseley St,27,Moseley St,NaN,2125,Dorchester,-71.054910,42.31989,...,NaN,NaN,NaN,"[{""date"":""2020-09-01T16:52:20.103"",""descriptio...",NaN,"[{""date"":""2020-09-01T16:52:20.103"",""descriptio...",NaN,"[{""date"":""2020-09-01T16:52:20.103"",""descriptio...",NaN,"[{""rs_prop_owner"":""MORAWIAK MARIA J"",""rs_prop_..."
2,107474,107474,205 Park St,205,Park St,NaN,2132,West Roxbury,-71.151550,42.28243,...,NaN,"[{""date"":""2017-07-11T11:22:00"",""description"":""...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""rs_prop_owner"":""SUPRIN KAREN A"",""rs_prop_fu..."
3,422070,422070,10R Spring Garden St,10R,Spring Garden St,NaN,2125,Dorchester,-71.053017,42.31854,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""rs_prop_owner"":""CURRAN JAMES J"",""rs_prop_fu..."
4,122952,122952,4 Sargent St,4,Sargent St,NaN,2125,Dorchester,-71.073990,42.31725,...,NaN,"[{""date"":""2018-07-17T13:10:00"",""description"":""...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""rs_prop_owner"":""COLLINS ANDRE"",""rs_prop_ful..."

In [9]:

'1930-to-1939.csv'
'1940-to-1949.csv'
'1950-to-1959.csv'
'1960-to-1969.csv'
'1970-to-1979.csv'
'1980-to-1999.csv'
'2016-to-2022.csv'


sample_1920 = pd.read_csv(
    '1920-to-1929.csv'
    , header = 0
    , nrows = 10
    ).filter(regex = 'rs_*')

sample_1920.head()

,rs_prop_sam_id,rs_prop_prim_sam_id,rs_prop_full_address,rs_prop_street_number,rs_prop_full_street_name,rs_prop_unit_number,rs_prop_zip_code,rs_prop_mailing_neighborhood,rs_prop_long,rs_prop_lat,rs_prop_pid,rs_prop_lu,rs_prop_owner,rs_prop_yr_built,rs_prop_yr_remod,rs_prop_living_area,rs_prop_bdrms,rs_prop_full_bth,rs_prop_half_bth
0,111444,111444,5-9 Pomeroy St,5-9,Pomeroy St,NaN,2134,Allston,-71.141129,42.353559,2101334000,R3,NARDELLI STEFANO,1920,1980,3828,8,3,0
1,58728,58728,32 Fletcher St,32,Fletcher St,NaN,2131,Roslindale,-71.136890,42.289180,2004763000,R2,OBRIEN JAMES C,1920,0,2960,7,2,0
2,62202,62202,105-107 Gallivan Blvd,105-107,Gallivan Blvd,NaN,2126,Mattapan,-71.073460,42.277830,1703387000,R2,MCDONOUGH JAMES B ETAL,1922,0,2288,4,2,0
3,150449,150449,54 Wilmington Ave,54,Wilmington Ave,NaN,2124,Dorchester,-71.077280,42.279380,1703063000,R1,DENNY VERNE O ETAL,1925,0,1536,3,1,0
4,150261,150261,192 Willow St,192,Willow St,NaN,2132,West Roxbury,-71.156240,42.292390,2007315000,R2,IOAKIMIDIS VASILIKI,1920,0,2604,6,2,0

In [10]:
'1940-to-1949.csv'
'1950-to-1959.csv'
'1960-to-1969.csv'
'1970-to-1979.csv'
'1980-to-1999.csv'
'2016-to-2022.csv'


sample_1930 = pd.read_csv(
    '1930-to-1939.csv'
    , header = 0
    , nrows = 10
    ).filter(regex = 'rs_*')

sample_1930.head()

,rs_prop_sam_id,rs_prop_prim_sam_id,rs_prop_full_address,rs_prop_street_number,rs_prop_full_street_name,rs_prop_unit_number,rs_prop_zip_code,rs_prop_mailing_neighborhood,rs_prop_long,rs_prop_lat,rs_prop_pid,rs_prop_lu,rs_prop_owner,rs_prop_yr_built,rs_prop_yr_remod,rs_prop_living_area,rs_prop_bdrms,rs_prop_full_bth,rs_prop_half_bth
0,119280,119280,11 Roxton St,11,Roxton St,NaN,2121,Dorchester,-71.080360,42.298100,1402610000,R3,HS LAND TRUST LLC,1930,NaN,4231,9,3,2
1,59618,59618,169 Foster St,169,Foster St,NaN,2135,Brighton,-71.157923,42.345122,2205231005,R2,DODGER LLC,1935,0.0,2040,4,2,0
2,100126,100126,215 N St,215,N St,NaN,2127,South Boston,-71.031360,42.331190,702652000,R1,FEENEY MICHAEL W,1930,0.0,1680,3,1,1
3,14422,14422,103-105 Bennett St,103-105,Bennett St,NaN,2135,Brighton,-71.158604,42.352070,2204389000,R2,LEVITZ LORETTA A,1930,1995.0,2250,4,2,1
4,121143,121143,77 Saint Gregory St,77,Saint Gregory St,NaN,2124,Dorchester,-71.070720,42.276050,1703284000,R1,HUMPHREY GEORGE W,1935,1989.0,1339,2,1,0

In [8]:

'1950-to-1959.csv'
'1960-to-1969.csv'
'1970-to-1979.csv'
'1980-to-1999.csv'
'2016-to-2022.csv'


sample_1940 = pd.read_csv(
    '1940-to-1949.csv'
    , header = 0
    , nrows = 10
    ).filter(regex = 'rs_*')

sample_1940.head()
sample_1940.dtypes

rs_prop_sam_id                    int64
rs_prop_prim_sam_id               int64
rs_prop_full_address             object
rs_prop_street_number             int64
rs_prop_full_street_name         object
rs_prop_unit_number             float64
rs_prop_zip_code                  int64
rs_prop_mailing_neighborhood     object
rs_prop_long                    float64
rs_prop_lat                     float64
rs_prop_pid                       int64
rs_prop_lu                       object
rs_prop_owner                    object
rs_prop_yr_built                  int64
rs_prop_yr_remod                float64
rs_prop_living_area               int64
rs_prop_bdrms                   float64
rs_prop_full_bth                float64
rs_prop_half_bth                float64
dtype: object

In [12]:

'1950-to-1959.csv'
'1960-to-1969.csv'
'1970-to-1979.csv'
'1980-to-1999.csv'
'2016-to-2022.csv'


sample_2016 = pd.read_csv(
    '2016-to-2022.csv'
    , header = 0
    , nrows = 10
    )

# sample_2016.head()
sample_2016.dtypes
# sample_2016.info

date               object
violation_type     object
description        object
address            object
neighborhood       object
zip_code            int64
parcel              int64
owner              object
year built          int64
year remodeled    float64
property_type      object
latitude          float64
longitude         float64
dtype: object

In [33]:
############################################################ Work with first file ############################################################
df1 = pd.read_csv('1700-to-1799.csv').filter(regex = 'rs_*')

file_names = (
    # '1700-to-1799.csv',
    '1800-to-1849.csv'
    , '1850-to-1899.csv'
    , '1900-to-1919.csv'
    , '1920-to-1929.csv'
    , '1930-to-1939.csv'
    , '1940-to-1949.csv'
    , '1950-to-1959.csv'
    , '1960-to-1969.csv'
    , '1970-to-1979.csv'
    , '1980-to-1999.csv'
    , '2000-to-2019.csv'
    # , '2016-to-2022.csv'
    )

# with open('2016-to-2022.csv') as f:
#     for line in f:
#         sample_foo(line.split(","))
    
for n in file_names:
    df2 = pd.read_csv(n).filter(regex = 'rs_*')
    df1 = pd.concat([df1, df2], ignore_index=True)

############################################################ Export ############################################################
# df1.to_csv('all_rentsmart.csv')
df1.to_parquet('all_rentsmart.parquet.gzip', compression = gzip)

In [2]:
# So I'm super smart and did not realize that the only actual violation data is in the 2016-to-2022.csv file
# All of the rest are just property records partitioned on date of construction(?)
# Therefore let's just work with that one, beautifully complete CSV
import pandas as pd

############################################################ Work with final file ############################################################
df = pd.read_csv('2016-to-2022.csv')


df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df.columns = ['date', 'violation_type', 'description', 'address', 'neighborhood', 'zip_code', 'parcel', 'owner', 'year_built', 'year_remodeled', 'property_type', 'latitude', 'longitude']
# df.astype({'year_built': 'int32', 'year_remodeled': 'int32'})
df.head()

# df.to_csv('2016-to-2022_cleaned.csv')

,date,violation_type,description,address,neighborhood,zip_code,parcel,owner,year_built,year_remodeled,property_type,latitude,longitude
0,2022-10-03,Enforcement Violations,Overfilling of barrel/dumpster,"324 Newbury St, 02115",Boston,2115,503060000,JP NEWBURY LLC MASS LLC,1915.0,2012.0,Mixed Use (Res. and Comm.),42.348400,-71.086030
1,2022-10-03,Enforcement Violations,Improper storage trash: res,"16 Temple St, 02114",Boston,2114,300023000,BOBSON RESIDENTIAL LLC,1900.0,2009.0,Residential 4 or more family,42.360901,-71.063548
2,2022-10-03,Enforcement Violations,Improper storage trash: res,"9-11 Pinckney St, 02114",Boston,2114,501896000,BARBER POLE LLC MASS LLC,1899.0,1985.0,Residential 7 or more units,42.358938,-71.065445
3,2022-10-03,Enforcement Violations,Overfilling of barrel/dumpster,"81 Newbury St, 02116",Boston,2116,501286000,AP NEWBURY STREET PORTFOLIO,1899.0,2015.0,Mixed Use (Res. and Comm.),42.351960,-71.074800
4,2022-10-03,Enforcement Violations,Improper storage trash: res,"416-418 Hanover St, 02113",Boston,2113,302054000,FOUR-16 HANOVER ST CONDO,1920.0,1983.0,Condominium Main*,42.366410,-71.052930

In [3]:
df.dtypes

date              datetime64[ns]
violation_type            object
description               object
address                   object
neighborhood              object
zip_code                   int64
parcel                     int64
owner                     object
year_built               float64
year_remodeled           float64
property_type             object
latitude                 float64
longitude                float64
dtype: object